<?php
// make sure to not include translations
$args['presets'][] = array(
    'title' => 'Default',
    'demo' => 'http://demo.mythemeshop.com/gridblog/',
    'thumbnail' => get_template_directory_uri().'/images/preset-thumb.jpg',
    'data' => '###a:44:{s:8:"last_tab";s:1:"0";s:8:"mts_logo";s:0:"";s:11:"mts_favicon";s:62:"http://demo.mythemeshop.com/gridblog/files/2015/05/favicon.png";s:14:"mts_touch_icon";s:0:"";s:14:"mts_metro_icon";s:0:"";s:20:"mts_twitter_username";s:0:"";s:15:"mts_header_code";s:0:"";s:14:"mts_copyrights";s:73:"Theme by <a href="http://mythemeshop.com/" rel="nofollow">MyThemeShop</a>";s:23:"mts_pagenavigation_type";s:1:"1";s:15:"mts_ajax_search";s:1:"0";s:14:"mts_responsive";s:1:"1";s:15:"mts_prefetching";s:1:"0";s:7:"mts_rtl";s:1:"0";s:16:"mts_color_scheme";s:7:"#fcce08";s:10:"mts_layout";s:8:"cslayout";s:16:"mts_first_footer";s:1:"1";s:20:"mts_first_footer_num";s:1:"3";s:12:"mts_bg_color";s:7:"#444444";s:14:"mts_bg_pattern";s:5:"hbg26";s:21:"mts_bg_pattern_upload";s:0:"";s:14:"mts_custom_css";s:0:"";s:20:"mts_show_primary_nav";s:1:"1";s:19:"mts_header_section2";s:1:"1";s:23:"mts_featured_categories";a:1:{i:0;a:4:{s:11:"group_title";s:0:"";s:10:"group_sort";s:1:"1";s:21:"mts_featured_category";s:6:"latest";s:30:"mts_featured_category_postsnum";s:1:"9";}}s:27:"mts_home_headline_meta_info";a:2:{s:7:"enabled";a:2:{s:6:"author";s:11:"Author Name";s:4:"date";s:4:"Date";}s:8:"disabled";a:2:{s:7:"comment";s:13:"Comment Count";s:8:"category";s:10:"Categories";}}s:22:"mts_single_post_layout";a:2:{s:7:"enabled";a:3:{s:7:"content";s:12:"Post Content";s:7:"related";s:13:"Related Posts";s:6:"author";s:10:"Author Box";}s:8:"disabled";a:1:{s:4:"tags";s:4:"Tags";}}s:26:"mts_related_posts_taxonomy";s:10:"categories";s:20:"mts_related_postsnum";s:1:"3";s:29:"mts_single_headline_meta_info";a:1:{s:7:"enabled";a:4:{s:6:"author";s:11:"Author Name";s:4:"date";s:4:"Date";s:8:"category";s:10:"Categories";s:7:"comment";s:13:"Comment Count";}}s:18:"mts_author_comment";s:1:"1";s:16:"mts_comment_date";s:1:"1";s:26:"mts_social_button_position";s:8:"floating";s:18:"mts_social_buttons";a:2:{s:7:"enabled";a:4:{s:7:"twitter";s:7:"Twitter";s:5:"gplus";s:11:"Google Plus";s:8:"facebook";s:13:"Facebook Like";s:9:"pinterest";s:9:"Pinterest";}s:8:"disabled";a:2:{s:8:"linkedin";s:8:"LinkedIn";s:7:"stumble";s:11:"StumbleUpon";}}s:20:"mts_sidebar_for_home";s:0:"";s:20:"mts_sidebar_for_post";s:0:"";s:20:"mts_sidebar_for_page";s:0:"";s:23:"mts_sidebar_for_archive";s:0:"";s:24:"mts_sidebar_for_category";s:0:"";s:19:"mts_sidebar_for_tag";s:0:"";s:20:"mts_sidebar_for_date";s:0:"";s:22:"mts_sidebar_for_author";s:0:"";s:22:"mts_sidebar_for_search";s:0:"";s:24:"mts_sidebar_for_notfound";s:0:"";s:15:"nhp-opts-backup";s:1:"1";}###'
);

?>